language: cpp
compiler:
  - gcc
  - clang

git:
  submodules: false

# whitelist
branches:
  only:
    - travis

# Install pre-reqs
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential python-psutil libfuse-dev git-all libicu-dev
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.tar.gz
  - tar xf cmake-2.8.12.tar.gz
  - cd cmake-2.8.12
  - ./bootstrap
  - make
  - sudo make install
  - cd ..

# Run the Build script
install:
  - git clone https://github.com/maidsafe/MaidSafe.git
  - git -C MaidSafe submodule update --init

# Run Tests
after_script:
  - cmake -HMaidSafe -Bbuild_maidsafe -DCMAKE_BUILD_TYPE=Debug 
  - cd MaidSafe
  - cmake .
  - make ExperCommon
